name: Build

on:
  push:

jobs:
  test:
    name: Build
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: docker build -t lhci .
      - name: Test
        run: docker run --rm lhci lhci healthcheck --fatal
